### ISSUE TITLE
ChromeOS 3.14.0: New Virtualbox cannot install, existing installations panic

### ISSUE THREAD

**Issue by nigelhealy** [divx118/crouton-packages#28] opened 2016-01-11 17:20 UTC
So I've had this issue for a few weeks now. I've spent much of the time seeking to eliminate myself as the cause, and try to fix it myself, and now can prove its a purely repeatable problem, now beyond my ideas to fix.

Take a new (e.g. Powerwash) Chromebook, developer mode. I have a Toshiba Chromebook 2 with

uname -a

Linux localhost 3.14.0 #1 SMP Wed Jan 6 22:01:46 PST 2016 x86_64 Intel(R) Core(TM) i3-5015U CPU @ 2.10GHz GenuineIntel GNU/Linux

Perform a clean crouton install of trusty
e.g. sudo sh ~/Downloads/crouton -r trusty -t xcfce

Enter the chroot e.g
sudo startxfce4

Then use this package's setup-header.sh to add headers and modify rc.local

Then install virtualbox. The method I used was 
deb http://download.virtualbox.org/virtualbox/debian trusty contrib
added to /etc/apt/sources.list
Add key
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -

update
sudo apt-get update

Then when you run this command, towards the end the Chromebook just reboots.
sudo apt-get install virtualbox-5.0

This is totally reproducible, I've done it many times.

It is not effacted if you logout/in of the chroot after the rc.local update before you install virtualbox.

I have installs which I had backups for, which were working with Virtualbox, then after ChromeOS update to 3.14.0 then Virtualbox would not run unless you ran the setup again, which then reboots the Chromebook as it builds new kernels.

I have also build my own kernels from scratch, downloading the ChromeOS kernel and that causes the exact same problem as I tell Virtualbox to setup.

Hence regardless of how you unique path is to ChromeOS 3.14.0, the same end result, Virtualbox is broke, will not run.

**Comment by divx118** [comment] 2016-01-11 19:09
@nigelhealy Yes unfortunately I don't have a chromebook with the 3.14 kernel so it is very hard for me to troubleshoot since this is a duplicate of #26 I will close this issue now. Thanks for reporting it at least is clear that all 3.14.0 kernels are affected. I see if I notice something in the recent kernel commits on chromeos.

**Closed by divx118** 2016-01-11 19:09 UTC
